document.addEventListener("DOMContentLoaded",()=>{const $=s=>document.querySelector(s);let active="network",query="";const modal=$("#authModal"),authForm=$("#authForm"),authTitle=$("#authTitle"),authSubmit=$("#authSubmit"),authSwitch=$("#authSwitch");let mode="login",industrialReady=false;

const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));

// Motivasi berganti setiap kali aplikasi dibuka. Kutipan sastra dipilih dari karya lama/public-domain; sisanya adalah kalimat orisinal My Learning OS.
const MOTIVATIONS=[
  {text:"I am no bird; and no net ensnares me; I am a free human being with an independent will.",source:"Charlotte Brontë — Jane Eyre (1847)"},
  {text:"I am not afraid of storms, for I am learning how to sail my ship.",source:"Louisa May Alcott — Little Women (1868)"},
  {text:"One sees clearly only with the heart. What is essential is invisible to the eye.",source:"Antoine de Saint-Exupéry — The Little Prince (1943)"},
  {text:"The mass of men lead lives of quiet desperation.",source:"Henry David Thoreau — Walden (1854)"},
  {text:"We are all in the gutter, but some of us are looking at the stars.",source:"Oscar Wilde — Lady Windermere's Fan (1892)"},
  {text:"Curiouser and curiouser!",source:"Lewis Carroll — Alice's Adventures in Wonderland (1865)"},
  {text:"Jangan menunggu siap. Mulailah, lalu biarkan proses membuatmu semakin siap.",source:"My Learning OS"},
  {text:"Satu halaman yang selesai hari ini lebih berharga daripada rencana seribu halaman besok.",source:"My Learning OS"},
  {text:"Belajar sedikit, ulangi terus, dan kemampuan yang terasa jauh akan menjadi kebiasaan.",source:"My Learning OS"},
  {text:"Tujuan besar dibangun dari keputusan kecil yang kamu ulangi setiap hari.",source:"My Learning OS"},
  {text:"Kalau hari ini terasa berat, kecilkan langkahnya—bukan mimpinya.",source:"My Learning OS"},
  {text:"Kamu tidak perlu menguasai semuanya hari ini. Kamu hanya perlu maju dari kemarin.",source:"My Learning OS"}
];
function setDailyMotivation(){const box=$("#motivationText"),source=$("#motivationSource");if(!box||!source)return;const quote=MOTIVATIONS[Math.floor(Math.random()*MOTIVATIONS.length)];box.textContent=quote.text;source.textContent=quote.source}

async function ensureIndustrial(){if(industrialReady||window.INDUSTRIAL_DETAIL){industrialReady=true;return}await new Promise((resolve,reject)=>{const s=document.createElement("script");s.src="data/industrial-details.js";s.onload=resolve;s.onerror=reject;document.head.appendChild(s)});industrialReady=true}
function industrialIds(){return(window.INDUSTRIAL_DETAIL?.semesters||[]).flatMap(s=>s.courses.flatMap(c=>c.items.map(x=>x.id)))}
function renderIndustrial(done){const q=query.trim();let completed=0,html="";for(const sem of(window.INDUSTRIAL_DETAIL?.semesters||[])){const courses=sem.courses.map(course=>({course,items:course.items.filter(x=>!q||(`${course.name} ${course.description} ${x.name} ${x.description}`).toLowerCase().includes(q))})).filter(x=>x.items.length);if(!courses.length)continue;html+=`<details class="semester" open><summary><strong>SEMESTER ${sem.semester}</strong><span>${courses.reduce((n,c)=>n+c.items.length,0)} materi</span></summary>`;for(const{course,items}of courses){const cd=course.items.filter(x=>done.includes(x.id)).length;completed+=cd;html+=`<details class="course" open><summary><div><strong>${esc(course.name)}</strong><small>${esc(course.description)}</small></div><span>${cd}/${course.items.length}</span></summary><div class="materialList">`;for(const x of items){const checked=done.includes(x.id);html+=`<label class="level material ${checked?"done":""}"><input type="checkbox" data-id="${x.id}" ${checked?"checked":""}><span class="levelText"><strong>${esc(x.name)}</strong><small>${esc(x.description||"")}</small></span></label>`}html+=`</div></details>`}html+=`</details>`}const allIds=industrialIds(),pct=allIds.length?Math.round(completed/allIds.length*100):0;$("#progressPct").textContent=pct+"%";$("#doneCount").textContent=completed;$("#remainCount").textContent=allIds.length-completed;$("#bar").style.width=pct+"%";$("#levelList").innerHTML=html||`<div class="empty">Materi tidak ditemukan.</div>`;$("#trackTitle").textContent="🏭 S1 Teknik Industri — BINUS Online";$("#trackCount").textContent=`${allIds.length} materi checklist`}
function stats(){return Object.entries(CURRICULUM).map(([key,t])=>{const done=Progress.get(key);return{key,title:t.title,icon:t.icon,total:t.items.length,done:done.length,pct:t.items.length?Math.round(done.length/t.items.length*100):0,next:t.items.find(x=>!done.includes(x.id))?.name||"Semua selesai"}})}
function dashboard(){const s=stats(),total=s.reduce((n,x)=>n+x.total,0),done=s.reduce((n,x)=>n+x.done,0),pct=total?Math.round(done/total*100):0;if($("#dashPct"))$("#dashPct").textContent=pct+"%";const d=$(".donut");if(d)d.style.background=`conic-gradient(#347cff 0 ${pct}%,#17243a ${pct}% 100%)`;if($("#dashDone"))$("#dashDone").textContent=done;if($("#dashTotal"))$("#dashTotal").textContent=total;const rows=$("#trackProgressCards");if(rows)rows.innerHTML=s.slice(0,5).map(x=>`<div class="track-row"><span>${x.icon} ${esc(x.title)}</span><div class="bar"><i style="width:${x.pct}%"></i></div><b>${x.pct}%</b></div>`).join("");const cards=$("#continueCards");if(cards)cards.innerHTML=s.slice(0,5).map(x=>`<article class="continue-card" data-track-card="${x.key}"><div class="ci">${x.icon}</div><h4>${esc(x.title)}</h4><p>${esc(x.next)}</p><div class="mini-bar"><i style="width:${x.pct}%"></i></div><span class="pct">${x.pct}%</span></article>`).join("")}
function render(){const u=Auth.getUser();$("#userEmail").textContent=u?.email||"Belum login";$("#logoutBtn").hidden=!u;$("#loginBtn").hidden=!!u;dashboard();const t=CURRICULUM[active],done=Progress.get(active);$("#trackTabs").innerHTML=Object.entries(CURRICULUM).map(([k,v])=>`<button class="tab ${k===active?"active":""}" data-track="${k}">${v.icon} ${esc(v.title)}</button>`).join("");if(active==="industrial"){renderIndustrial(done);return}const items=t.items.filter(x=>x.name.toLowerCase().includes(query)),total=t.items.length,pct=total?Math.round(done.length/total*100):0;$("#progressPct").textContent=pct+"%";$("#doneCount").textContent=done.length;$("#remainCount").textContent=total-done.length;$("#bar").style.width=pct+"%";$("#levelList").innerHTML=items.map(x=>`<label class="level ${done.includes(x.id)?"done":""}"><input type="checkbox" data-id="${x.id}" ${done.includes(x.id)?"checked":""}><span class="levelText"><strong>${esc(x.name)}</strong>${x.description?`<small>${esc(x.description)}</small>`:""}</span></label>`).join("")||`<div class="empty">Tidak ada level yang cocok.</div>`;$("#trackTitle").textContent=`${t.icon} ${t.title}`;$("#trackCount").textContent=`${total} checklist`}
function openAuth(m){mode=m;authTitle.textContent=m==="login"?"Login":"Daftar";authSubmit.textContent=m==="login"?"Login":"Buat akun";authSwitch.textContent=m==="login"?"Belum punya akun? Daftar":"Sudah punya akun? Login";$("#authError").textContent="";authForm.reset();modal.showModal()}
authForm.addEventListener("submit",async e=>{e.preventDefault();authSubmit.disabled=true;$("#authError").textContent="";try{const email=$("#email").value,password=$("#password").value;if(mode==="login")await Auth.login(email,password);else await Auth.register(email,password);modal.close();render()}catch(err){$("#authError").textContent=err.message||"Gagal memproses akun."}finally{authSubmit.disabled=false}});authSwitch.addEventListener("click",()=>openAuth(mode==="login"?"register":"login"));$("#loginBtn").onclick=()=>openAuth("login");$("#logoutBtn").onclick=()=>Auth.logout().then(render);document.addEventListener("click",async e=>{const tab=e.target.closest("[data-track]");const card=e.target.closest("[data-track-card]");if(tab||card){active=(tab||card).dataset.track||(tab||card).dataset.trackCard;query="";$("#search").value="";if(active==="industrial")await ensureIndustrial();render();document.getElementById("trackTabs").scrollIntoView({behavior:"smooth",block:"center"})}});$("#levelList").addEventListener("change",e=>{if(e.target.matches("input[data-id]")){Progress.toggle(active,Number(e.target.dataset.id));render()}});$("#search").addEventListener("input",e=>{query=e.target.value.toLowerCase();render()});$("#checkAll").onclick=()=>{if(active==="industrial")Progress.set(active,industrialIds());else Progress.all(active,CURRICULUM[active].items.length);render()};$("#clearAll").onclick=()=>{Progress.clear(active);render()};$("#resetAll").onclick=()=>{if(confirm("Reset semua checklist track ini?")){Progress.clear(active);render()}};["startLearning","viewAllTracks","viewAllTracks2"].forEach(id=>$("#"+id)?.addEventListener("click",()=>document.getElementById("trackTabs").scrollIntoView({behavior:"smooth",block:"center"})));document.addEventListener("authchange",render);document.addEventListener("progresschange",render);setDailyMotivation();Auth.init().then(async()=>{if(active==="industrial")await ensureIndustrial();render()})});