(function(){
const VAPID_PUBLIC_KEY='BHKKo_OAyp0cz2aH-CPxycNYcpaiRBiVIYxQdDgHlVU75zcGUuF_q2FCopPEXPruj-QhdroXR2om_sN-SnO3tSU';
window.BINUS_VAPID_PUBLIC_KEY=window.BINUS_VAPID_PUBLIC_KEY||VAPID_PUBLIC_KEY;
function urlBase64ToUint8Array(base64String){const padding='='.repeat((4-base64String.length%4)%4);const base64=(base64String+padding).replace(/-/g,'+').replace(/_/g,'/');const raw=atob(base64);return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)));}
function ensurePushCard(){let card=document.getElementById('push-card');if(card)return card;const calendar=document.getElementById('calendar');if(!calendar)return null;card=document.createElement('section');card.id='push-card';card.className='wa-card push-card';card.innerHTML='<div class="push-copy"><p class="eyebrow">NOTIFIKASI HP</p><h2>Jangan sampai ketinggalan kelas</h2><p class="muted">Aktifkan notifikasi agar jadwal kelas, tugas, dan ujian dari kalender BINUS dapat mengingatkanmu langsung di HP.</p><div class="push-rules"><span>📚 Kelas: 1 jam sebelum</span><span>📝 Tugas: 1 hari sebelum</span><span>🧪 Ujian: 1 hari sebelum</span></div></div><div class="push-action"><button id="enablePushBtn" class="primary" type="button">🔔 Aktifkan Notifikasi HP</button><div id="pushStatus" class="push-status">Belum diaktifkan pada perangkat ini.</div></div>';calendar.insertAdjacentElement('afterend',card);return card;}
function getEls(){ensurePushCard();return{card:document.getElementById('push-card'),button:document.getElementById('enablePushBtn'),status:document.getElementById('pushStatus')}}
function setStatus(text,kind=''){const{status}=getEls();if(!status)return;status.textContent=text;status.dataset.state=kind;}
function setButton(text,disabled=false){const{button}=getEls();if(!button)return;button.textContent=text;button.disabled=disabled;}
function preparePushUi(){const{card,button}=getEls();if(!card||!button)return;card.hidden=false;card.style.display='';if(button.dataset.pushBound==='1')return;button.dataset.pushBound='1';button.addEventListener('click',setupPush);refreshPushState();}
async function refreshPushState(){const{button}=getEls();if(!button)return;if(!window.isSecureContext||!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window)){setStatus('Notifikasi push membutuhkan browser modern dan koneksi HTTPS.');setButton('Notifikasi tidak didukung',true);return;}if(Notification.permission==='denied'){setStatus('Notifikasi diblokir. Aktifkan izin notifikasi untuk situs ini dari pengaturan browser.','error');return;}try{const registration=await navigator.serviceWorker.register('./sw.js',{scope:'./'});await navigator.serviceWorker.ready;const subscription=await registration.pushManager.getSubscription();if(subscription){setStatus('✅ Perangkat ini sudah terdaftar untuk notifikasi.');setButton('✅ Notifikasi Aktif',true);}}catch(error){console.error('Push init error',error);setStatus('Gagal menyiapkan notifikasi: '+(error.message||error),'error');}}
async function setupPush(){const{button}=getEls();if(!button)return;if(!window.isSecureContext||!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window)){setStatus('Notifikasi push membutuhkan browser modern dan koneksi HTTPS.');return;}if(!window.bxSupabase){setStatus('Silakan tunggu sampai aplikasi selesai terhubung ke server.','error');return;}setButton('⏳ Mengaktifkan...',true);try{const{data:{user}}=await window.bxSupabase.auth.getUser();if(!user){setButton('🔔 Aktifkan Notifikasi HP');setStatus('Silakan login terlebih dahulu.','error');document.getElementById('loginBtn')?.click();return;}const permission=await Notification.requestPermission();if(permission!=='granted'){setButton('🔔 Aktifkan Notifikasi HP');setStatus(permission==='denied'?'Izin notifikasi diblokir. Aktifkan izin situs ini di pengaturan browser.':'Izin notifikasi belum diberikan.','error');return;}const registration=await navigator.serviceWorker.register('./sw.js',{scope:'./'});await navigator.serviceWorker.ready;let subscription=await registration.pushManager.getSubscription();if(!subscription)subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlBase64ToUint8Array(window.BINUS_VAPID_PUBLIC_KEY)});const json=subscription.toJSON();if(!json.endpoint||!json.keys?.p256dh||!json.keys?.auth)throw new Error('Data subscription tidak lengkap');const{error}=await window.bxSupabase.from('binus_push_subscriptions').upsert({user_id:user.id,endpoint:json.endpoint,p256dh:json.keys.p256dh,auth:json.keys.auth,user_agent:navigator.userAgent},{onConflict:'user_id,endpoint'});if(error)throw new Error('Gagal menyimpan perangkat: '+error.message);const{error:settingError}=await window.bxSupabase.from('binus_notification_settings').upsert({user_id:user.id,push_enabled:true,timezone:'Asia/Jakarta'},{onConflict:'user_id'});if(settingError)throw new Error('Gagal menyimpan pengaturan: '+settingError.message);setStatus('✅ Notifikasi HP aktif di perangkat ini.');setButton('✅ Notifikasi Aktif',true);}catch(error){console.error('Push setup error',error);setButton('🔔 Aktifkan Notifikasi HP');setStatus('Gagal mengaktifkan notifikasi: '+(error.message||error),'error');}}
function init(){preparePushUi();const observer=new MutationObserver(preparePushUi);observer.observe(document.body,{childList:true,subtree:true});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
